### ISSUE TITLE
Integrating with Autopsy

### ISSUE THREAD

**Issue by WriteCodeEveryday** [abrignoni/ALEAPP#48]
Would it be possible to turn this into a module for Autopsy?

The standard Android Analyzer module is decent, but this has a bit more data.

**Comment by ydkhatri** [comment]
Possible with limited features, but unlikely due to the reasons stated on Autopsy's website:
[https://www.sleuthkit.org/autopsy/docs/api-docs/4.15.0/mod_dev_py_page.html](https://www.sleuthkit.org/autopsy/docs/api-docs/4.15.0/mod_dev_py_page.html)

Autopsy uses Jython, which severely restricts what you can do. Main limitations are:
+ Limited to Python 2.7 (as of Autopsy 3.1.3)
+ Can't use Python libraries that have native code
